### ISSUE TITLE
Frequency counters are not supported

### ISSUE THREAD

**Issue by brenc** [WoltLab/node-haproxy-peers#1]
Hello! Thank you so much for open sourcing this. I have been looking for something to help parse the peers protocol for some time.

Not sure if this was only posted for the conference or if this will be getting worked on here at all, but I thought I'd just note that this library doesn't appear to support frequency counters. If I add one like:

`table quota type string len 100 size 10000 store gpc0,http_req_rate(1m)`

I get a stack trace:

```
demo_1       | 2021-12-22T20:49:20.979Z manager:demo connecting
demo_1       | 2021-12-22T20:49:20.987Z manager:haproxy:peers:connection sending hello
demo_1       | 2021-12-22T20:49:20.988Z manager:stream read blocks
demo_1       | 2021-12-22T20:49:20.992Z manager:haproxy:peers:connection received status 200
demo_1       | 2021-12-22T20:49:20.993Z manager:haproxy:peers:connection sending heartbeat
demo_1       | 2021-12-22T20:49:20.994Z manager:haproxy:peers:connection sending synchronization request
demo_1       | 2021-12-22T20:49:20.994Z manager:demo Started sync
demo_1       | 2021-12-22T20:49:21.036Z manager:haproxy:peers:protocol-parser attempting to parse table definition
demo_1       | 2021-12-22T20:49:21.070Z manager:demo Error: Incorrect packet length (total)
demo_1       |     at PeerParser.tryParseTableDefinition (/app/src/haproxy/peers/protocol-parser.ts:247:13)
demo_1       |     at PeerParser.tryParseUpdateMessage (/app/src/haproxy/peers/protocol-parser.ts:162:31)
demo_1       |     at /app/src/haproxy/peers/protocol-parser.ts:120:46
demo_1       |     at PeerParser.tryParse (/app/src/haproxy/peers/protocol-parser.ts:127:22)
demo_1       |     at PeerParser._transform (/app/src/haproxy/peers/protocol-parser.ts:388:31)
demo_1       |     at PeerParser.Transform._write (node:internal/streams/transform:184:23)
demo_1       |     at writeOrBuffer (node:internal/streams/writable:389:12)
demo_1       |     at _write (node:internal/streams/writable:330:10)
demo_1       |     at PeerParser.Writable.write (node:internal/streams/writable:334:10)
demo_1       |     at Socket.ondata (node:internal/streams/readable:754:22)
demo_1       | 2021-12-22T20:49:21.071Z manager:haproxy:peers:connection stopping heartbeats
```

Something like `table quota type string len 100 size 10000 store gpt0,conn_cur,sess_cnt,http_req_cnt` is parsed just fine but as soon as I add a frequency counter it crashes.

I'll see if I can get this working with frequency counters but I don't know that I will be able to be much help here to be honest. I have never worked with binary data processing before and it looks to be pretty far beyond me!

**Comment by TimWolla** [comment]
Hi Brendon

> Hello! Thank you so much for open sourcing this. I have been looking for something to help parse the peers protocol for some time.

Thank you for this positive feedback!

> Not sure if this was only posted for the conference or if this will be getting worked on here at all, but I thought I'd just note that this library doesn't appear to support frequency counters. If I add one like:

Not sure whether you've seen my slides or watched the conference. This is something I acknowledged in my talk: The implementation is incomplete and implements just the parts we need (and the ones that could be added easily, because the necessary logic basically already exists).

This repository was spun out of our larger internal project and only minimally adapted to get it working in a standalone fashion. As such it will *not* be maintained to the level of an actual standalone Open Source project, it's not part of our core business. As an example we'll not version this or publish to npm. That said, I plan to keep this repository updated with any changes we are making internally. 

I've also just briefly looked into the error in frequency counter handling: Frequency counters are special, because they are the only parameterized data type (the parameter being the `1m` you have in your config). For this reason they include extra data in the stick table definition message and that's what is causing the protocol parser to desync.

Are you interested in actually reading the frequency counters, or do you just want the process not to crash? The latter should be easy-ish to add (but this would still be a low priority given the reasons above).

**Comment by brenc** [comment]
Hi Tim!

>Not sure whether you've seen my slides or watched the conference.

They have not posted the video yet but I will be sure to watch when they do.

>As such it will not be maintained to the level of an actual standalone Open Source project

OK no problem. Would it be best for me to publish changes to my own fork then? I have added support for frequency counters in the table definition message handling and am now adding it to the entry update message. I'd also like to add tests, linting, to publish to NPM, etc.

>Are you interested in actually reading the frequency counters

The plan is to read the counters. I've added them to the table definition like this (I created a stick table with every type of data possible, including all the counter types with various time periods):
```
demo_1       |   counters: [
demo_1       |     [ 3, 86400000 ],
demo_1       |     [ 5, 60000 ],
demo_1       |     [ 8, 60000 ],
demo_1       |     [ 10, 79200000 ],
demo_1       |     [ 12, 60000 ],
demo_1       |     [ 14, 60000 ],
demo_1       |     [ 16, 60000 ],
demo_1       |     [ 18, 60000 ],
demo_1       |     [ 21, 60000 ]
demo_1       |   ]
```

**Comment by TimWolla** [comment]
Sorry for not getting back to you earlier. I was on vacation over the holidays.

> Would it be best for me to publish changes to my own fork then?

You already closed this issue, however: Yes, that would be best. This repository effectively being a subtree split of our internal repository makes it hard to integrate external changes.

I've shortly looked into the changes you made. One word of caution: I've taken great care to implement the implementation as close to the spec as possible and that explains some of the more complicated code paths that you simplified. As an example the status message of the handshake is defined to be [terminated by the newline](https://github.com/haproxy/haproxy/blob/f5e94b2f47b45c7aebbe390b02abd1ff7b810981/doc/peers-v2.0.txt#L48) and my version actually scans for the newline, whereas you simply read 4 bytes off the socket and assume this to be a three-digit status + LF. While this most likely holds for the foreseeable future, it is not technically correct according to the spec.

**Comment by brenc** [comment]
>Sorry for not getting back to you earlier.

No problem! I figured you were on vacation and it wasn't that big of a deal anyway.

>You already closed this issue, however: Yes, that would be best.

OK  - I thought so which is partly why I closed the ticket. I ended up making so many changes that I knew it would be next to impossible to easily incorporate them back so I figured I would just continue to commit to my own repo.

>it is not technically correct according to the spec.

Thanks for pointing this out! This has mainly been a learning exercise for me so that's why I made a lot of the changes I did. I was experimenting with ways to simplify that initial handshake process and things like that.

Most of this stuff is completely new to me (working with binary data, buffers, the peers spec, etc.) so I'm trying to figured out how all of this works too. I have the spec docs and the source open and have been attempting to read through it as I go along but I have to admit that understanding it all has been a bit of a challenge.

I managed to implement the rest of the key types (binary, IPv6, IP) and the frequency counters as well. Soon I will start adding tests and other things. Eventually I'd like to publish this to NPM.

Thanks again!

**Comment by TimWolla** [comment]
> They have not posted the video yet but I will be sure to watch when they do.

FYI: The video is online now: https://www.haproxy.com/user-spotlight-series/using-haproxy-peers-for-real-time-quota-tracking/

I've also just committed my slide deck: https://github.com/WoltLab/node-haproxy-peers/blob/main/slides.pdf

**Comment by brenc** [comment]
Interesting presentation. Thanks for sharing!
